export const SPIRITUAL_MASTERS = [
  "Acyuta Priya Das RNS (APD)",
  "Advaita Acharya Das BTS (AAD)",
  "Adikarta Das (AKD)",
  "Asita Krishna Swami TKG (AKS)",
  "Atmanivedana Swami BSDS (AVS)",
  "Bhakti Ananda Haridas Goswami (BAHG) BSDS",
  "Bhakti Anugraha Janardana Swami GKG (BAJS)",
  "Bhakti Asraya Vaisnava Swami GKG (BAVS)",
  "Bhaktivaibhava Swami (BVS)",
  "Bhakti Bhagavatamrita Kesava Swami PVS (BBKS)",
  "Bhakti Bhrnga Govinda Swami (BBGS)",
  "Bhakti Caitanya Swami (BCAIS)",
  "Bhakti Carudesna Swami BTS (BCDS)",
  "Bhakti Dayita Adipurusha Swami GGS (BDAS)",
  "Bhakti Dhira Damodara Swami BTS (BDDS)",
  "Bhakti Gaurava Narayan Swami TKG (BGNS)",
  "Bhakti Gauravani Goswami (BGVG)",
  "Bhakti Prabhava Swami BCS (BPRS)",
  "Bhakti Prabhupada-vrata Damodara Swami (BPDS)",
  "Bhakti Pran Gopinath Swami GGS (BPGS)",
  "Bhakti Prema Swami BCS (BHPS)",
  "Bhakti Raghava Swami (BRS)",
  "Bhakti Ratnakara Ambarisa Swami GKG (BRAS)",
  "Bhakti Sundar Goswami (BSG)",
  "Bhakti Vasudeva Swami BTS (BHVS)",
  "Bhakti Vijnana Goswami RNS (BVG)",
  "Bhakti Vikasa Swami (BVKS)",
  "Bhaktivyasa Tirtha Swami BSDS (BVTS)",
  "Bhakti VV Narasimha Swami (BVVNS)",
  "Bhakti-bhusana Swami (BBS)",
  "Bhaktimarga Swami (BMS)",
  "Bhaktipada Goswami SRS (BPG)",
  "Bhurijana Das (BJD)",
  "Bir Krsna Das Goswami (BKG)",
  "Caitanya Avatari Das JPS (CAD)",
  "Caitanya Candra Caran Das JPS (CCCD)",
  "Candra Mukha Swami HDG (CMKS)",
  "Candramauli Swami (CMS)",
  "Caru Das (CD)",
  "Danavir Goswami (DG)",
  "Dayavan Swami RSD (DS)",
  "Devakinandan Das MVG (DND)",
  "Devamrita Swami (DAS)",
  "Dhanvantari Swami (DVS)",
  "Dhirasanta Das Goswami (DDG) ",
  "Drutakarma Das (DKD)",
  "Gauranga Prem Swami JPS (GRPS)",
  "Giridhari Swami (GDS)",
  "Gopaswami Das (GSD)",
  "Guru Prasad Swami (GPS)",
  "Haladhara Swami GGS (HDS)",
  "Hanumatpresaka Swami (HPS)",
  "Harivilas Das (HVD)",
  "Hrdayananda dasa Goswami (HDG)",
  "Indradyumna Swami (IDS)",
  "Janananda dasa Goswami (JG)",
  "Jayadvaita Swami (JAS)",
  "Jayapataka Swami (JPS)",
  "Jivananda Das (JND)",
  "Kalakantha Das (KKD)",
  "Kavicandra Swami (KVCS)",
  "Kesava Bharati dasa Goswami (KBDG)",
  "Kratu Das (KRD)",
  "Kripamoya Das (KMD)",
  "Krsna Ksetra Swami (KRKS)",
  "Lokanath Swami (LOK)",
  "Madana-mohana Das MG (MM)",
  "Madan Gopal Das SDG (MGD)",
  "Madhu Sevita Das (MSD)",
  "Mahadyuti Swami (MDS)",
  "Mahaman Das (MMD)",
  "Mahaprabhu Swami SRS (MPS)",
  "Mahatma Das (MD)",
  "Mahavisnu Swami (MVS)",
  "Mani Bandha Das NRS (MBD)",
  "Manonatha Das (MND)",
  "Matsya Avatara Das (MAD)",
  "Medhavi Das (MDD)",
  "Narayani Devi Dasi (NDD)",
  "Navayogendra Swami (NYS)",
  "Niranjana Swami (NRS)",
  "Partha Sarathi Das Goswami (PSDG)",
  "Patita Pavana Das IDS (PPD)",
  "Prabodhananda Saraswati Swami GKG (PSS)",
  "Prahladananda Swami (PAS)",
  "Purushatraya Swami (PTS)",
  "Radhacaran Das TKG (RCD)",
  "Radha Govinda Das SRS (RGD)",
  "Radha Govinda Swami (RGM)",
  "Radha Krishna Das TKG (RKD)",
  "Radhanath Swami (RNS)",
  "Rama Govinda Swami KDS (RMGS)",
  "Ravindra Svarupa Das (RVSD)",
  "Revati Raman Das JPS (RRD)",
  "Romapada Swami (RPS)",
  "Rtadhvaja Swami (RTS)",
  "Sacinandana Swami (SNS)",
  "Samik Rsi Das (SRD)",
  "Sankarsana Das (SDA)",
  "Satyadeva Das (SDD)",
  "Sikhi Mahiti Das (SMD)",
  "Sivarama Swami (SRS)",
  "Smita Krsna Swami (SKS)",
  "Sridhama Das (SD)",
  "Srivas Das BTS (SVD)",
  "Subhaga Swami (SSM)",
  "Sundarananda Das GGS (SND)",
  "Sukadeva Swami RNS (SDS)",
  "Umapati Das GKG (UPD)",
  "Vaisesika Das (VSD)",
  "Varsana Swami (VS)",
  "Vatsala Das (VD)",
  "Vasu Srestha Das JPS (VSD)",
  "Vedavyasapriya Swami (VVPS)",
  "Virabahu Das (VBD)",
  "Yadunandana Swami SDG (YNS)",
  "Yamunacarya Das Goswami HDG (YDG)"
];
